Repository Projeto-Fragelli/Trezentos-App, pull requests merged in 2018-11, with the labels that each got.

#83 Create Issue Template
  .github/ISSUE_TEMPLATE/issue-us.md
Labels: Documentation

#84 Adds Issue Template
  .github/ISSUE_TEMPLATE/issue.md
Labels: Documentation

#85 Create Pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#86 Solve #80 Criar código de contribuição
  CONTRIBUTING.md
Labels: Documentation

#92 Solve #91_Erro_de_Digitacao
  .idea/caches/build_file_checksums.ser
  app/src/main/res/layout/activity_class.xml
  app/src/main/res/layout/fragment_info_class.xml
Labels: bug

#93 Solve #90_Exibir_nome_professor_aba_explorar
  app/src/main/java/fga/mds/gpp/trezentos/Controller/UserClassControl.java
Labels: Android, bug
